CREATE TABLE monitoramento_calor (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  temperatura FLOAT,
  umidade FLOAT,
  pressao FLOAT,
  status VARCHAR2(30),
  data_insercao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


