# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMKjJFg6uOhtlgMe7bkLyh2nZy0lXysd
"""

# 1. Instalar e importar bibliotecas
!pip install scikit-learn joblib --quiet

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

# 2. Carregar e preparar os dados
df = pd.read_csv("/content/INMET_CO_DF_A001_BRASILIA_07-05-2000_A_31-12-2000.CSV",
                 sep=";", encoding="latin1", skiprows=8)

df = df.rename(columns={
    'DATA (YYYY-MM-DD)': 'data',
    'TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C)': 'temp_max',
    'TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)': 'temp_atual',
    'UMIDADE RELATIVA DO AR, HORARIA (%)': 'umidade',
    'PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB)': 'pressao_max',
    'PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB)': 'pressao_min'
})

df.replace(['////', '///', '-9999'], pd.NA, inplace=True)

for col in ['temp_max', 'temp_atual', 'umidade', 'pressao_max', 'pressao_min']:
    df[col] = df[col].astype(str).str.replace(',', '.')
    df[col] = pd.to_numeric(df[col], errors='coerce')

df['pressao'] = (df['pressao_max'] + df['pressao_min']) / 2
df.dropna(subset=['temp_max', 'temp_atual', 'umidade', 'pressao'], inplace=True)

# 3. Treinar modelo com 3 variáveis
X = df[['temp_atual', 'umidade', 'pressao']]
y = df['temp_max']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

modelo = RandomForestRegressor(n_estimators=100, random_state=42)
modelo.fit(X_train, y_train)

# 4. Avaliação
y_pred = modelo.predict(X_test)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Erro médio absoluto: {mae:.2f} °C")
print(f"Coeficiente de determinação (R²): {r2:.2f}")

# 5. Salvar modelo
joblib.dump(modelo, "modelo_previsao_amanha.pkl")